version: '3'

services:
  analysisapi:
    build:
      context: ../../
      dockerfile: ./analysis-api/docker/node/Dockerfile
    image: analysisapi
    container_name: analysisapi
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      - APP
      - PORT
      - EXTERNAL_URL
      - HOSTNAME
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
